version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
